[package]
name = "parsere"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"

[dependencies]
once_cell = "*"
regex = "*"

[dependencies.parsere-derive]
path = "../parsere-derive"
